development:
  adapter: mysql2
  database: maps_development
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: maps_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: maps_production
  pool: 5
  timeout: 5000
